version: "3.8"
services:

  app:
    build: ./docker/image/nginx
    image: $COMPOSE_PROJECT_NAME-nginx
    container_name: $COMPOSE_PROJECT_NAME-nginx
    depends_on:
      - db
      - phpfpm
    links:
      - phpfpm
      - db
      - elastic
      - mailcatcher
      - setup
    volumes: &appvolumes
      - ./html:/var/www/html
      - ./docker/image/php/auth.json:/var/www/.composer/auth.json
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.ssh/id_rsa:/var/www/.ssh/id_rsa
      - $HOME/.ssh/known_hosts:/var/www/.ssh/known_hosts
    ports:
      - 80
    networks:
      default:
        ipv4_address: 172.20.0.3
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=magento.loc
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  phpfpm:
    build: ./docker/image/php
    image: $COMPOSE_PROJECT_NAME-php
    container_name: $COMPOSE_PROJECT_NAME-php
    depends_on:
      - db
    links:
      - db
      - elastic
    volumes: *appvolumes
    ports:
      - 9000
    networks:
      default:
        ipv4_address: 172.20.0.4
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=magento.loc
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  db:
    image: mysql:5.7
    container_name: $COMPOSE_PROJECT_NAME-db
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 3306
    networks:
      default:
        ipv4_address: 172.20.0.5
    env_file: ./docker/image/db/.env

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: $COMPOSE_PROJECT_NAME-elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      default:
        ipv4_address: 172.20.0.9
    environment:
      - node.name=elastic
      - cluster.name=magento-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  mailcatcher:
    build: ./docker/image/mailcatcher
    image: $COMPOSE_PROJECT_NAME-mailcatcher
    container_name: $COMPOSE_PROJECT_NAME-mailcatcher
    ports:
      - 1080
      - 1025
    networks:
      default:
        ipv4_address: 172.20.0.8

  setup:
    image: $COMPOSE_PROJECT_NAME-php
    container_name: $COMPOSE_PROJECT_NAME-setup
    command: 'su -c "/usr/local/bin/start-setup" -s /bin/sh www-data'
    links:
      - db
    volumes: *appvolumes
    env_file: ./docker/image/setup/.env

networks:
  default:
    name: magento
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
