version: "3.8"
services:

  app:
    build: ./docker/image/nginx
    image: ${COMPOSE_PROJECT_NAME}-nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    depends_on:
      - db
      - es
      - php
      - cron
      - setup
      - mailcatcher
    volumes: &appvolumes
      - ./html:/var/www/html
      - ./docker/socket:/var/www/run
      - ./docker/image/php/auth.json:/var/www/.composer/auth.json
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
      - ${HOME}/.ssh/id_rsa:/var/www/.ssh/id_rsa
      - ${HOME}/.ssh/known_hosts:/var/www/.ssh/known_hosts
    ports:
      - 80:80

  db:
    image: mariadb:10.5.8
    container_name: ${COMPOSE_PROJECT_NAME}-db
    volumes:
      - ./docker/data/db:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: ./docker/image/db/.env

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: ${COMPOSE_PROJECT_NAME}-es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    env_file: ./docker/image/es/.env

  php:
    build: ./docker/image/php
    image: ${COMPOSE_PROJECT_NAME}-php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    depends_on:
      - db
    volumes: *appvolumes
    ports:
      - 9000
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  cron:
    build:
      context: ./docker/image/cron
      args:
        - PHP_IMAGE_NAME=${COMPOSE_PROJECT_NAME}-php
    image: ${COMPOSE_PROJECT_NAME}-cron
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    depends_on:
      - php
    volumes: *appvolumes

  setup:
    build:
      context: ./docker/image/setup
      args:
        - PHP_IMAGE_NAME=${COMPOSE_PROJECT_NAME}-php
    image: ${COMPOSE_PROJECT_NAME}-setup
    container_name: ${COMPOSE_PROJECT_NAME}-setup
    depends_on:
      - php
    volumes: *appvolumes
    env_file: ./docker/image/setup/.env

  mailcatcher:
    build: ./docker/image/mailcatcher
    image: ${COMPOSE_PROJECT_NAME}-mailcatcher
    container_name: ${COMPOSE_PROJECT_NAME}-mailcatcher
    ports:
      - 1080:1080
      - 1025

networks:
  default:
    name: magento
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
