version: "3"
services:

  app:
    build: ./docker/nginx/
    image: vulpea/magento2-nginx
    container_name: $COMPOSE_PROJECT_NAME-nginx
    depends_on:
      - db
      - phpfpm
    links:
      - db
      - phpfpm
      - elastic
    volumes: &appvolumes
      - ./html:/var/www/html
      - ./docker/composer:/var/www/.composer
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.ssh/id_rsa:/var/www/.ssh/id_rsa
      - $HOME/.ssh/known_hosts:/var/www/.ssh/known_hosts
    ports:
      - 80
    networks:
      default:
        ipv4_address: 172.20.0.3
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=magento.loc
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  phpfpm:
    build: ./docker/php/
    image: vulpea/magento2-php
    container_name: $COMPOSE_PROJECT_NAME-php
    depends_on:
      - db
    links:
      - db
      - elastic
    volumes: *appvolumes
    ports:
      - 9000
    networks:
      default:
        ipv4_address: 172.20.0.4
    env_file: ./docker/env/setup.env
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=magento.loc
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  db:
    image: mysql:5.7
    container_name: $COMPOSE_PROJECT_NAME-db
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 3306
    networks:
      default:
        ipv4_address: 172.20.0.5
    env_file: ./docker/env/mysql.env

  setup:
    image: vulpea/magento2-php
    container_name: $COMPOSE_PROJECT_NAME-setup
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    env_file: ./docker/env/setup.env

  mailcatcher:
    build: ./docker/mailcatcher
    container_name: vulpea_mailcatcher_os
    image: vulpea/mailcatcher:0.6.4
    ports:
      - 1080
      - 1025
    networks:
      default:
        ipv4_address: 172.20.0.8

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: $COMPOSE_PROJECT_NAME-elastic
    environment:
      - node.name=elastic
      - cluster.name=magento-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      default:
        ipv4_address: 172.20.0.9

networks:
  default:
    name: magento
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
